###

POST http://localhost:8080/api/board
Content-Type: application/json

{
  "title": "My first project"
}

###

GET http://localhost:8080/api/board
X-ACCESS-TOKEN:eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIciwiY3JlYXRlZEF0IjoiMjAyMS0wNS0yNlQyMTo1NDo0Ni43ODIiLCJyb2xlIjoiVVNFUiIsIm5hbWUiOiJEaWFuYSIsImVtYWlsIjoiZGlhbmFtMEByYW1ibGVyLnJ1In0.yo_yYWtZDElT30DrWCVYoQmV310fl36X-10jhK0ehfA

###

PUT http://localhost:8080/api/board/10
Content-Type: application/json
X-ACCESS-TOKEN:Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJkaWFuYW0wQHJhbWJsZXIucnUiLCJpYXQiOjE2MjA3NTgxOTAsImV4cCI6MTYyMDg0NDU5MH0.pEc8bESJxiuwE4zkps2MZm9MGI1hamjPL1-dSEAZVEQUc-d4efgozd8xEgfH5V3evhr15CocRHBSnHiGpr2aBQ

{
  "email": "piauaw@gmail.com"
}